version: 2.1


workflows:
  tests:
    jobs:
      - plone6py311

jobs:

  plone6py311:
    resource_class: medium
    docker:
      - image: webcloud7/plone-test:6.0.5-py311
      - image: webcloud7/keycloak-test:22.0.2.1
        environment:
        - KEYCLOAK_ADMIN: 'admin'
        - KEYCLOAK_ADMIN_PASSWORD: 'admin'
        - KC_HEALTH_ENABLED: 'true'
        - KC_METRICS_ENABLED: 'true'

    environment:
      PIP_FIND_LINKS: /wheelhouse/
      zope_i18n_compile_mo_files: "true"
      WSGI_SERVER_PORT: 65035

    steps:
      - checkout
      - run: apt-get update && apt-get install -y pkg-config libxml2-dev libxmlsec1-dev libxmlsec1-openssl
      - run: make test VENV_FOLDER=.

